// given a list of ames in a "dirty" condition, normilize the list.
// you can look at the list, but cannot edit the source list.

// part 1:
// seperate firstname and last name into seperate fields.

// part 2:
// make sure names are capitalized properly.

// part 3:
// handle dropping middle names or dirty parts of the field (parts of the string that are not first name or last name)

// part 4:
// Handdle Name exceptions, like last or firstname that would properly include multiple capitilization such as McDonald.

// part 5: EXTRA!!!
// remove duplicate names from the list.



const names =[
    "Jimmy MacDonald", 
    "Sebastian Lee",
    "Jorge Page",
    "Lisa-Marie Skinner",
    "Haseeb Drew",
    "Kristie Dalton",
    "Camille Harrington",
    "Elijah Douglas",
    "Maddy O'Reilly",
    "Nel Collier",
    "Finley Lindsey",
    "Sylvie Tyson",
    "Susan S. Steptoe",
    "Keziah Murray",
    "Amina Goldsmith",
    "Gabrielius Hardin",
    "Kimberley Donnelly",
    "Ana-Maria Stella Ritter",
    "Alexa McNeil",
    "Shabaz Torres",
    "Ashlyn Dolores Rosario",
    "Eleasha Farrow",
    "Usamah  F Clay",
    "Liam Valencia",
    "P.T. Barnum",
    "Bronwyn Roach",
    "Muhammad Koch",
    "Ellie-Rose Novak",
    "Cairo Clegg",
    "Tyla dit Villeneuve",
    "Anish Ridley",
    "Kush George",
    "Iestyn Humphries",
    "Winifred Parkes",
    "Gurpreet Gibbs",
    "Ayda Boyle",
    "Farah Anthony",
    "Nelly Rogers",
    "Roxy Allison",
    "Hunter Finch",
    "Gabriele Small (inactive)",
    "Miss Lilly-Ann Baker",
    "Mccauley Marsh",
    "Alexandru Perez",
    "Harman Bartlett",
    "Osian Patel",
    "Silas Kelley",
    "Ritchie Moreno",
    "Yara Riley",
    "Nadir Preece",
    "Malaika Gallagher",
    "Kaylem Rivas",
    "Zakir Chan",
    "Yusra Emerson",
    "Delores Ward",
    "Sameeha Bradley",
    "Ruby-May Conway",
    "Abiha Escobar",
    "Roshan Irvine",
    "Eve Whitmore",
    "Abraham Hester",
    "Shani Lawrence",
    "Dev Knott",
    "Tammy Vargas",
    "Tazmin Bowen",
    "Codie Reilly",
    "Mackenzie Werner",
    "Huey Lovell",
    "Lillie-Mae Talley",
    "Marianne Whitaker",
    "Alesha Romero",
    "Emilija Gay",
    "Kayson Hendricks",
    "Anthony Bains",
    "Gabriella Summers",
    "Kirsty Lozano",
    "Oriana Lees",
    "Alexi Buck",
    "Thelma Paine",
    "Maureen Atkins",
    "Olaf Rowe",
    "Lorcan Foreman",
    "Anam Lucero",
    "William Bradshaw",
    "Sanjeev Albert",
    "Bear Doyle",
    "Ocean Cornish",
    "Romana Lamb",
    "Huda Raymond",
    "Dilan Logan",
    "Ursula Warner",
    "Jorge Gray",
    "Adem McConnell",
    "Giuseppe Taylor",
    "Isabel Justice",
    "Samiyah Shaw",
    "Tala Salas",
    "Stacey Connor",
    "Agata Hurley",
    "Fardeen Edge",
    "Jerry MacDonald (this is the son)",
    "Luna Reynolds",
    "Adelaide Avila",
    "Isra Key",
    "Yasser Diaz",
    "Blair Leon",
    "Abid Paterson",
    "Hester Hodgson",
    "Isaak Hammond",
    "Maisie Kaufman",
    "Flora Robbins",
    "Kourtney Bloom",
    "Jaspal Senior",
    "Zahara Reyes",
    "Braxton McCormick III",
    "Karam May",
    "Harri Charles",
    "Malakai Oneil",
    "Brian Lovell",
    "Finnley Pratt",
    "Penelope Oliver",
    "Junayd Bridges",
    "Stanislaw Parra",
    "Seb Roberson",
    "Abel D'Aloia",
    "Jaeden Leigh",
    "Kelsea Rush",
    "Teagan Glass",
    "Dr. Malcolm Burt",
    "Haleemah Durham",
    "Tilly Flynn",
    "temp record: Pedro Wilkes",
    "Frank Espinoza",
    "Avneet Molina",
    "Lowri Lyon",
    "Eric Huerta - she is no longer interested",
    "Enid Skinner",
    "Lukas Huff",
    "Holli O'Quinn",
    "Devon Massey",
    "Yara Munoz",
    "Abe Marion Neal",
    "Derek Gilmour",
    "Rees Combs",
    "Mamie Gutierrez",
    "Ellouise P. Krause",
    "Siraj Adamson",
    "Keeleigh Diaz",
    "Fahima Mcneill",
    "Damian Young",
    "Priya Crowther",
    "Warren Hendricks",
    "Zakk Michael",
    "Bronte Armitage",
    "Madiha Hassan",
    "Joanna Hogan",
    "Murat Leblanc",
    "Alicia Henson",
    "Natasha Villegas",
    "Travis Garrett",
    "Huzaifa Mcgregor",
    "Leland Vinson",
    "Isra Branch",
    "Jemimah Chung",
    "Leyla Kirk",
    "Jocelyn Stuart",
    "Indigo Lim",
    "Rickie Boyer",
    "Cory Cash",
    "Dougie Hook",
    "Ameera Alvarado",
    "Aj Huynh",
    "Roberson Seb",
    "Jill Knight",
    "Christian Hill",
    "Malachi Talbot",
    "Wesley Lindsay",
    "Hilda Vu",
    "Ranveer McClain",
    "Miley Almond",
    "Cadi Wardle",
    "Josephine Ellwood",
    "Moshe Smith",
    "Abubakr O'Ryan",
    "D'Lilah Lena Rhodes",
    "Sasha McFadden",
    "REEM DUKE",
    "Rheanna Stewart",
    "Neil Gregory",
    "Ellenor Goddard",
    "Adriana Bain",
    "Eira Ferguson",
    "TRE Cain",
    "Edward Gaines",
    "Emily Monaghan",
    "Gillian Briggs",
    "Josef Dougherty",
    "Maariya Isabel de los Toros-Camacho",
    "Judy Gillespie",
    "Ebrahim Sweeney",
    "Elouise Joyce",
    "Tyler Jackson",
    "Ezra Duran",
    "Isaac Welch",
    "Jayda Mccartney",
    "Oliwier Jordan",
    "Beulah Christie",
    "Rudy Patton",
    "Ivie Bird",
    "Sarah Tanner",
    "Zackary Rivers",
    "Matt Castro",
    "Kelsey Leach",
    "Felicia Carr",
    "Evie-Mae Wilkins"
]